#ifndef PDOUBLEGENETIC_GLOBAL_H
#define PDOUBLEGENETIC_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PDOUBLEGENETIC_LIBRARY)
#  define PDOUBLEGENETIC_EXPORT Q_DECL_EXPORT
#else
#  define PDOUBLEGENETIC_EXPORT Q_DECL_IMPORT
#endif

#endif // PDOUBLEGENETIC_GLOBAL_H
