#ifndef ISLANDMULTISTART_GLOBAL_H
#define ISLANDMULTISTART_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ISLANDMULTISTART_LIBRARY)
#define ISLANDMULTISTART_EXPORT Q_DECL_EXPORT
#else
#define ISLANDMULTISTART_EXPORT Q_DECL_IMPORT
#endif

#endif // ISLANDMULTISTART_GLOBAL_H
