#ifndef NEURALMINIMIZER_GLOBAL_H
#define NEURALMINIMIZER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NEURALMINIMIZER_LIBRARY)
#  define NEURALMINIMIZER_EXPORT Q_DECL_EXPORT
#else
#  define NEURALMINIMIZER_EXPORT Q_DECL_IMPORT
#endif

#endif // NEURALMINIMIZER_GLOBAL_H
