#ifndef INTERVALMETHOD_GLOBAL_H
#define INTERVALMETHOD_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(INTERVALMETHOD_LIBRARY)
#  define INTERVALMETHOD_EXPORT Q_DECL_EXPORT
#else
#  define INTERVALMETHOD_EXPORT Q_DECL_IMPORT
#endif

#endif // INTERVALMETHOD_GLOBAL_H
