#ifndef PARALLELGENETIC_GLOBAL_H
#define PARALLELGENETIC_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PARALLELGENETIC_LIBRARY)
#  define PARALLELGENETIC_EXPORT Q_DECL_EXPORT
#else
#  define PARALLELGENETIC_EXPORT Q_DECL_IMPORT
#endif

#endif // PARALLELGENETIC_GLOBAL_H
