#ifndef DOUBLEGENETIC_GLOBAL_H
#define DOUBLEGENETIC_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DOUBLEGENETIC_LIBRARY)
#  define DOUBLEGENETIC_EXPORT Q_DECL_EXPORT
#else
#  define DOUBLEGENETIC_EXPORT Q_DECL_IMPORT
#endif

#endif // DOUBLEGENETIC_GLOBAL_H
